export default defineEventHandler((event) => {
    return {
        "nome": "Apartamento 402",
        "capa": "https://deepacupuntura.com/apart402/capa.jpg",
        "img": { 
            1: "https://deepacupuntura.com/apart402/1.jpg",
            2: "https://deepacupuntura.com/apart402/2.jpg",
            3: "https://deepacupuntura.com/apart402/3.jpg",
            // 4: "https://deepacupuntura.com/apart402/4.jpg",
            // 5: "https://deepacupuntura.com/apart402/5.jpg",
            // 6: "https://deepacupuntura.com/apart402/6.jpg",
            // 7: "https://deepacupuntura.com/apart402/7.jpg",
            // 8: "https://deepacupuntura.com/apart402/8.jpg",
            // 9: "https://deepacupuntura.com/apart402/9.jpg",
            // 10: "https://deepacupuntura.com/apart402/10.jpg",
            // 11: "https://deepacupuntura.com/apart402/11.jpg",
            // 12: "https://deepacupuntura.com/apart402/12.jpg",
            // 13: "https://deepacupuntura.com/apart402/13.jpg",
            // 14: "https://deepacupuntura.com/apart402/14.jpg",
            // 15: "https://deepacupuntura.com/apart402/15.jpg",
            // 16: "https://deepacupuntura.com/apart402/16.jpg",
            // 17: "https://deepacupuntura.com/apart402/17.jpg",
            // 18: "https://deepacupuntura.com/apart402/18.jpg",
            // 19: "https://deepacupuntura.com/apart402/19.jpg",
            // 20: "https://deepacupuntura.com/apart402/20.jpg",
            // 21: "https://deepacupuntura.com/apart402/21.jpg",
            // 22: "https://deepacupuntura.com/apart402/22.jpg",
            // 23: "https://deepacupuntura.com/apart402/23.jpg",
            // 24: "https://deepacupuntura.com/apart402/24.jpg",
            // 25: "https://deepacupuntura.com/apart402/25.jpg",
        },
    }
})
