export default defineEventHandler((event) => {
    return {
        "nome": "Apartamento 402",
        "capa": "https://isadorapecanha.com/apart402/capa.png",
        "description": `Lorem ipsum dolor sit amet consectetur 
        adipisicing elit. Porro, nobis cupiditate! Delectus 
        labore aliquid minima cupiditate culpa, odio assumenda 
        nihil corrupti. Dolor explicabo excepturi harum fuga
         iste eaque soluta aliquam?`,
        "comodos": ["Sala", "Cozinha", "Suite", "Varanda", "Banheiros"],
        "sala": { 
            7.1: "https://isadorapecanha.com/apart402/7-min.jpg",
            8.1: "https://isadorapecanha.com/apart402/8-min.jpg",
            9.1: "https://isadorapecanha.com/apart402/21-min.jpg",
            10.1: "https://isadorapecanha.com/apart402/10-min.jpg",
            11.1: "https://isadorapecanha.com/apart402/11-min.jpg",
            12.1: "https://isadorapecanha.com/apart402/12-min.jpg",
            13.1: "https://isadorapecanha.com/apart402/13-min.jpg",
            14.1: "https://isadorapecanha.com/apart402/14-min.jpg",
            18.1: "https://isadorapecanha.com/apart402/18-min.jpg",
            21.1: "https://isadorapecanha.com/apart402/9-min.jpg",
            7: "https://isadorapecanha.com/apart402/7.jpg",
            8: "https://isadorapecanha.com/apart402/8.jpg",
            9: "https://isadorapecanha.com/apart402/21.jpg",
            10: "https://isadorapecanha.com/apart402/10.jpg",
            11: "https://isadorapecanha.com/apart402/11.jpg",
            12: "https://isadorapecanha.com/apart402/12.jpg",
            13: "https://isadorapecanha.com/apart402/13.jpg",
            14: "https://isadorapecanha.com/apart402/14.jpg",
            18: "https://isadorapecanha.com/apart402/18.jpg",
            21: "https://isadorapecanha.com/apart402/9.jpg",
        },
        "cozinha": { 
            15.1: "https://isadorapecanha.com/apart402/15-min.jpg",
            16.1: "https://isadorapecanha.com/apart402/16-min.jpg",
            17.1: "https://isadorapecanha.com/apart402/17-min.jpg",
            15: "https://isadorapecanha.com/apart402/15.jpg",
            16: "https://isadorapecanha.com/apart402/16.jpg",
            17: "https://isadorapecanha.com/apart402/17.jpg",
        },
        "suite": { 
            2.1: "https://isadorapecanha.com/apart402/2-min.jpg",
            3.1: "https://isadorapecanha.com/apart402/3-min.jpg",
            4.1: "https://isadorapecanha.com/apart402/4-min.jpg",
            2: "https://isadorapecanha.com/apart402/2.jpg",
            3: "https://isadorapecanha.com/apart402/3.jpg",
            4: "https://isadorapecanha.com/apart402/4.jpg",
        },
        "varanda": { 
            1.1: "https://isadorapecanha.com/apart402/1-min.jpg",
            22.1: "https://isadorapecanha.com/apart402/22-min.jpg",
            23.1: "https://isadorapecanha.com/apart402/23-min.jpg",
            24.1: "https://isadorapecanha.com/apart402/24-min.jpg",
            25.1: "https://isadorapecanha.com/apart402/25-min.jpg",
            1: "https://isadorapecanha.com/apart402/1.jpg",
            22: "https://isadorapecanha.com/apart402/22.jpg",
            23: "https://isadorapecanha.com/apart402/23.jpg",
            24: "https://isadorapecanha.com/apart402/24.jpg",
            25: "https://isadorapecanha.com/apart402/25.jpg",
        },
        "banheiros": { 
            5.1: "https://isadorapecanha.com/apart402/5-min.jpg",
            6.1: "https://isadorapecanha.com/apart402/6-min.jpg",
            19.1: "https://isadorapecanha.com/apart402/19-min.jpg",
            20.1: "https://isadorapecanha.com/apart402/20-min.jpg",
            5: "https://isadorapecanha.com/apart402/5.jpg",
            6: "https://isadorapecanha.com/apart402/6.jpg",
            19: "https://isadorapecanha.com/apart402/19.jpg",
            20: "https://isadorapecanha.com/apart402/20.jpg",
        },
    }
})
